[project]
name = "pdi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "nost17", email = "erick.personal16@outlook.com" }]
dependencies = [
  "matplotlib>=3.11.1",
  "numpy>=2.5.2",
  "pillow>=12.3.0",
]

[project.scripts]
tp-0 = "pdi.tp0:main"
tp-1 = "pdi.tp1:main"
tp-2 = "pdi.tp2:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
